# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Network/Servers/athena.teokem.lu.se/Volumes/Data/Users/mikael/faunus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Network/Servers/athena.teokem.lu.se/Volumes/Data/Users/mikael/faunus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Network/Servers/athena.teokem.lu.se/Volumes/Data/Users/mikael/faunus/CMakeFiles /Network/Servers/athena.teokem.lu.se/Volumes/Data/Users/mikael/faunus/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Network/Servers/athena.teokem.lu.se/Volumes/Data/Users/mikael/faunus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libfaunus

# Build rule for target.
libfaunus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libfaunus
.PHONY : libfaunus

# fast build rule for target.
libfaunus/fast:
	$(MAKE) -f src/CMakeFiles/libfaunus.dir/build.make src/CMakeFiles/libfaunus.dir/build
.PHONY : libfaunus/fast

#=============================================================================
# Target rules for targets named libfaunus.a

# Build rule for target.
libfaunus.a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libfaunus.a
.PHONY : libfaunus.a

# fast build rule for target.
libfaunus.a/fast:
	$(MAKE) -f src/CMakeFiles/libfaunus.a.dir/build.make src/CMakeFiles/libfaunus.a.dir/build
.PHONY : libfaunus.a/fast

#=============================================================================
# Target rules for targets named binding

# Build rule for target.
binding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binding
.PHONY : binding

# fast build rule for target.
binding/fast:
	$(MAKE) -f src/examples/CMakeFiles/binding.dir/build.make src/examples/CMakeFiles/binding.dir/build
.PHONY : binding/fast

#=============================================================================
# Target rules for targets named isobaric

# Build rule for target.
isobaric: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isobaric
.PHONY : isobaric

# fast build rule for target.
isobaric/fast:
	$(MAKE) -f src/examples/CMakeFiles/isobaric.dir/build.make src/examples/CMakeFiles/isobaric.dir/build
.PHONY : isobaric/fast

#=============================================================================
# Target rules for targets named manybody

# Build rule for target.
manybody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manybody
.PHONY : manybody

# fast build rule for target.
manybody/fast:
	$(MAKE) -f src/examples/CMakeFiles/manybody.dir/build.make src/examples/CMakeFiles/manybody.dir/build
.PHONY : manybody/fast

#=============================================================================
# Target rules for targets named pka

# Build rule for target.
pka: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pka
.PHONY : pka

# fast build rule for target.
pka/fast:
	$(MAKE) -f src/examples/CMakeFiles/pka.dir/build.make src/examples/CMakeFiles/pka.dir/build
.PHONY : pka/fast

#=============================================================================
# Target rules for targets named pkaGC

# Build rule for target.
pkaGC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pkaGC
.PHONY : pkaGC

# fast build rule for target.
pkaGC/fast:
	$(MAKE) -f src/examples/CMakeFiles/pkaGC.dir/build.make src/examples/CMakeFiles/pkaGC.dir/build
.PHONY : pkaGC/fast

#=============================================================================
# Target rules for targets named printpotential

# Build rule for target.
printpotential: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 printpotential
.PHONY : printpotential

# fast build rule for target.
printpotential/fast:
	$(MAKE) -f src/examples/CMakeFiles/printpotential.dir/build.make src/examples/CMakeFiles/printpotential.dir/build
.PHONY : printpotential/fast

#=============================================================================
# Target rules for targets named spce

# Build rule for target.
spce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spce
.PHONY : spce

# fast build rule for target.
spce/fast:
	$(MAKE) -f src/examples/CMakeFiles/spce.dir/build.make src/examples/CMakeFiles/spce.dir/build
.PHONY : spce/fast

#=============================================================================
# Target rules for targets named spceMI

# Build rule for target.
spceMI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spceMI
.PHONY : spceMI

# fast build rule for target.
spceMI/fast:
	$(MAKE) -f src/examples/CMakeFiles/spceMI.dir/build.make src/examples/CMakeFiles/spceMI.dir/build
.PHONY : spceMI/fast

#=============================================================================
# Target rules for targets named twobody

# Build rule for target.
twobody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 twobody
.PHONY : twobody

# fast build rule for target.
twobody/fast:
	$(MAKE) -f src/examples/CMakeFiles/twobody.dir/build.make src/examples/CMakeFiles/twobody.dir/build
.PHONY : twobody/fast

#=============================================================================
# Target rules for targets named twobody-hof

# Build rule for target.
twobody-hof: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 twobody-hof
.PHONY : twobody-hof

# fast build rule for target.
twobody-hof/fast:
	$(MAKE) -f src/examples/CMakeFiles/twobody-hof.dir/build.make src/examples/CMakeFiles/twobody-hof.dir/build
.PHONY : twobody-hof/fast

#=============================================================================
# Target rules for targets named widom_cube

# Build rule for target.
widom_cube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 widom_cube
.PHONY : widom_cube

# fast build rule for target.
widom_cube/fast:
	$(MAKE) -f src/examples/CMakeFiles/widom_cube.dir/build.make src/examples/CMakeFiles/widom_cube.dir/build
.PHONY : widom_cube/fast

#=============================================================================
# Target rules for targets named widom_sphere

# Build rule for target.
widom_sphere: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 widom_sphere
.PHONY : widom_sphere

# fast build rule for target.
widom_sphere/fast:
	$(MAKE) -f src/examples/CMakeFiles/widom_sphere.dir/build.make src/examples/CMakeFiles/widom_sphere.dir/build
.PHONY : widom_sphere/fast

#=============================================================================
# Target rules for targets named bulk

# Build rule for target.
bulk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bulk
.PHONY : bulk

# fast build rule for target.
bulk/fast:
	$(MAKE) -f legacy/fortran/CMakeFiles/bulk.dir/build.make legacy/fortran/CMakeFiles/bulk.dir/build
.PHONY : bulk/fast

#=============================================================================
# Target rules for targets named docclean

# Build rule for target.
docclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docclean
.PHONY : docclean

# fast build rule for target.
docclean/fast:
	$(MAKE) -f doc/CMakeFiles/docclean.dir/build.make doc/CMakeFiles/docclean.dir/build
.PHONY : docclean/fast

#=============================================================================
# Target rules for targets named manual

# Build rule for target.
manual: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manual
.PHONY : manual

# fast build rule for target.
manual/fast:
	$(MAKE) -f doc/CMakeFiles/manual.dir/build.make doc/CMakeFiles/manual.dir/build
.PHONY : manual/fast

#=============================================================================
# Target rules for targets named manualul

# Build rule for target.
manualul: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manualul
.PHONY : manualul

# fast build rule for target.
manualul/fast:
	$(MAKE) -f doc/CMakeFiles/manualul.dir/build.make doc/CMakeFiles/manualul.dir/build
.PHONY : manualul/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... libfaunus"
	@echo "... libfaunus.a"
	@echo "... binding"
	@echo "... isobaric"
	@echo "... manybody"
	@echo "... pka"
	@echo "... pkaGC"
	@echo "... printpotential"
	@echo "... spce"
	@echo "... spceMI"
	@echo "... twobody"
	@echo "... twobody-hof"
	@echo "... widom_cube"
	@echo "... widom_sphere"
	@echo "... bulk"
	@echo "... docclean"
	@echo "... manual"
	@echo "... manualul"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

