# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mikael/faunus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mikael/faunus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mikael/faunus/CMakeFiles /Users/mikael/faunus/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mikael/faunus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fns

# Build rule for target.
fns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fns
.PHONY : fns

# fast build rule for target.
fns/fast:
	$(MAKE) -f classes/CMakeFiles/fns.dir/build.make classes/CMakeFiles/fns.dir/build
.PHONY : fns/fast

#=============================================================================
# Target rules for targets named GCpka

# Build rule for target.
GCpka: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GCpka
.PHONY : GCpka

# fast build rule for target.
GCpka/fast:
	$(MAKE) -f examples/CMakeFiles/GCpka.dir/build.make examples/CMakeFiles/GCpka.dir/build
.PHONY : GCpka/fast

#=============================================================================
# Target rules for targets named isobaric

# Build rule for target.
isobaric: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isobaric
.PHONY : isobaric

# fast build rule for target.
isobaric/fast:
	$(MAKE) -f examples/CMakeFiles/isobaric.dir/build.make examples/CMakeFiles/isobaric.dir/build
.PHONY : isobaric/fast

#=============================================================================
# Target rules for targets named manybody

# Build rule for target.
manybody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manybody
.PHONY : manybody

# fast build rule for target.
manybody/fast:
	$(MAKE) -f examples/CMakeFiles/manybody.dir/build.make examples/CMakeFiles/manybody.dir/build
.PHONY : manybody/fast

#=============================================================================
# Target rules for targets named pka

# Build rule for target.
pka: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pka
.PHONY : pka

# fast build rule for target.
pka/fast:
	$(MAKE) -f examples/CMakeFiles/pka.dir/build.make examples/CMakeFiles/pka.dir/build
.PHONY : pka/fast

#=============================================================================
# Target rules for targets named twobody

# Build rule for target.
twobody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 twobody
.PHONY : twobody

# fast build rule for target.
twobody/fast:
	$(MAKE) -f examples/CMakeFiles/twobody.dir/build.make examples/CMakeFiles/twobody.dir/build
.PHONY : twobody/fast

#=============================================================================
# Target rules for targets named twobody-hof

# Build rule for target.
twobody-hof: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 twobody-hof
.PHONY : twobody-hof

# fast build rule for target.
twobody-hof/fast:
	$(MAKE) -f examples/CMakeFiles/twobody-hof.dir/build.make examples/CMakeFiles/twobody-hof.dir/build
.PHONY : twobody-hof/fast

#=============================================================================
# Target rules for targets named widom

# Build rule for target.
widom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 widom
.PHONY : widom

# fast build rule for target.
widom/fast:
	$(MAKE) -f examples/CMakeFiles/widom.dir/build.make examples/CMakeFiles/widom.dir/build
.PHONY : widom/fast

#=============================================================================
# Target rules for targets named docclean

# Build rule for target.
docclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docclean
.PHONY : docclean

# fast build rule for target.
docclean/fast:
	$(MAKE) -f doc/CMakeFiles/docclean.dir/build.make doc/CMakeFiles/docclean.dir/build
.PHONY : docclean/fast

#=============================================================================
# Target rules for targets named manual

# Build rule for target.
manual: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manual
.PHONY : manual

# fast build rule for target.
manual/fast:
	$(MAKE) -f doc/CMakeFiles/manual.dir/build.make doc/CMakeFiles/manual.dir/build
.PHONY : manual/fast

#=============================================================================
# Target rules for targets named manualul

# Build rule for target.
manualul: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manualul
.PHONY : manualul

# fast build rule for target.
manualul/fast:
	$(MAKE) -f doc/CMakeFiles/manualul.dir/build.make doc/CMakeFiles/manualul.dir/build
.PHONY : manualul/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... fns"
	@echo "... GCpka"
	@echo "... isobaric"
	@echo "... manybody"
	@echo "... pka"
	@echo "... twobody"
	@echo "... twobody-hof"
	@echo "... widom"
	@echo "... docclean"
	@echo "... manual"
	@echo "... manualul"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

