cp output.dat output$1.dat
cp gofr.dat gofr$1.dat
cp mucorr.dat mucorr$1.dat
cp mucorr_angle.dat mucorr_angle$1.dat
cp mucorr_dist.dat mucorr_dist$1.dat
cp KW.dat KW$1.dat
cp confout.pqr confout$1.pqr
cp stockmayer.wrl stockmayer$1.wrl
cp stockmayer.run stockmayer$1.run
cp nemo.cpp nemo$1.cpp
cp pot_dipdip.dat pot_dipdip$1.dat
cp state state$1
