mv output$2.dat $1/.
mv gofr$2.dat $1/.
mv mucorr$2.dat $1/.
mv mucorr_angle$2.dat $1/.
mv mucorr_dist$2.dat $1/.
mv KW$2.dat $1/.
mv confout$2.pqr $1/.
mv stockmayer$2.wrl $1/.
mv pot_dipdip$2.dat $1/.
mv proTotDip_x$2.dat $1/.
mv proTotDip_y$2.dat $1/.
mv proTotDip_z$2.dat $1/.
mv proTotDip_x_box$2.dat $1/.
mv proTotDip_y_box$2.dat $1/.
mv proTotDip_z_box$2.dat $1/.
mv out$2.xtc $1/.
cp stockmayer$2.run $1/.
cp nemo$2.cpp $1/. 
cp nemo$2 $1/.
cp state$2 $1/.
