#!/usr/bin/env python

import os
import sys
from IPython.Shell import IPShellEmbed

# find where we are running from and extend Python path
filename_self = os.path.abspath(__file__)
path_faunus = os.path.dirname(filename_self)
sys.path.insert(0, path_faunus)

# now we can import faunus
import pyfaunus


# run the shell
# TODO customize it, print intro message
ipshell = IPShellEmbed()
print pyfaunus.faunus_splash(),
ipshell()

