#!/bin/bash

function mkinput() {
echo '
{
"processes" :
{
"H-Asp" : { "bound":"HASP" , "free":"ASP" , "pKd":4.0  , "pX":'$pH' },
"H-Ctr" : { "bound":"HCTR" , "free":"CTR" , "pKd":2.6  , "pX":'$pH' },
"H-Glu" : { "bound":"HGLU" , "free":"GLU" , "pKd":4.4  , "pX":'$pH' },
"H-His" : { "bound":"HHIS" , "free":"HIS" , "pKd":6.3  , "pX":'$pH' },
"H-Arg" : { "bound":"HARG" , "free":"ARG" , "pKd":12.0 , "pX":'$pH' },
"H-Ntr" : { "bound":"HNTR" , "free":"NTR" , "pKd":7.5  , "pX":'$pH' },
"H-Cys" : { "bound":"HCYS" , "free":"CYS" , "pKd":10.8 , "pX":'$pH' },
"H-Tyr" : { "bound":"HTYR" , "free":"TYR" , "pKd":9.6  , "pX":'$pH' },
"H-Lys" : { "bound":"HLYS" , "free":"LYS" , "pKd":10.4 , "pX":'$pH' },
"K1"    : { "bound":"H3PO4", "free":"H2PO4","pKd":2.12,  "pX":'$pH' },
"K2"    : { "bound":"H2PO4", "free":"HPO4", "pKd":7.21,  "pX":'$pH' },
"K3"    : { "bound":"HPO4",  "free":"PO4",  "pKd":12.67, "pX":'$pH' }
},

"atomlist" :
{
"H3PO4":  { "q":0,  "r":2.0 },
"H2PO4":  { "q":-1, "r":2.0 },
"HPO4" :  { "q":-2, "r":2.0 },
"PO4"  :  { "q":-3, "r":2.0 },
"BPTI" :  { "q":7.3, "r":12.29 },
"Na"   :  { "q": 1, "r":1.9, "mw":22.99 },
"Cl"   :  { "q":-1, "r":1.7, "mw":35.45 },
"I"    :  { "q":-1, "r":2.0, "mw":1 },
"SCN"  :  { "q":-1, "r":2.0, "mw":1 },
"ASP"  :  { "q":-1, "r":3.6, "mw":110 },
"HASP" :  { "q":0,  "r":3.6, "mw":110 },
"LASP" :  { "q":2,  "r":3.6, "mw":110 },
"CTR"  :  { "q":-1, "r":2.0, "mw":16 },
"HCTR" :  { "q":0,  "r":2.0, "mw":16 },
"GLU"  :  { "q":-1, "r":3.8, "mw":122 },
"HGLU" :  { "q":0,  "r":3.8, "mw":122 },
"LGLU" :  { "q":2,  "r":3.8, "mw":122 },
"HIS"  :  { "q":0,  "r":3.9, "mw":130 },
"HHIS" :  { "q":1,  "r":3.9, "mw":130 },
"NTR"  :  { "q":0,  "r":2.0, "mw":14 },
"HNTR" :  { "q":1,  "r":2.0, "mw":14 },
"TYR"  :  { "q":-1, "r":4.1, "mw":154 },
"HTYR" :  { "q":0,  "r":4.1, "mw":154 },
"LYS"  :  { "q":0,  "r":3.7, "mw":116 },
"HLYS" :  { "q":1,  "r":3.7, "mw":116 },
"CYS"  :  { "q":-1, "r":3.6, "mw":103 },
"HCYS" :  { "q":0,  "r":3.6, "mw":103 },
"ARG"  :  { "q":0,  "r":4.0, "mw":144 },
"HARG" :  { "q":1,  "r":4.0, "mw":144 },
"ALA"  :  { "q":0,  "r":3.1, "mw":66 },
"ILE"  :  { "q":0,  "r":3.6, "mw":102 },
"LEU"  :  { "q":0,  "r":3.6, "mw":102 },
"MET"  :  { "q":0,  "r":3.8, "mw":122 },
"PHE"  :  { "q":0,  "r":3.9, "mw":138 },
"PRO"  :  { "q":0,  "r":3.4, "mw":90 },
"TRP"  :  { "q":0,  "r":4.3, "mw":176 },
"VAL"  :  { "q":0,  "r":3.4, "mw":90 },
"SER"  :  { "q":0,  "r":3.3, "mw":82 },
"THR"  :  { "q":0,  "r":3.5, "mw":94 },
"ASN"  :  { "q":0,  "r":3.6, "mw":108 },
"GLN"  :  { "q":0,  "r":3.8, "mw":120 },
"GLY"  :  { "q":0,  "r":2.9, "mw":54 }
}
}
' > wall.json

echo "2
HIS  0   0.00   0.00   0.00    0   130.  3.0
HIS  0   0.00   0.00   6.00    0   130.  3.0
" > testmolecule.aam

echo "
atomlist               wall.json
eq_processfile         wall.json
loop_macrosteps        10
loop_microsteps        $micro

temperature            298.15  # Kelvin
epsilon_r              78.7    # Water dielectric const
gouychapman_phi0       0       # unitless i.e. e*phi/kT
gouychapman_linearize  yes

lj_eps                 0.05    # kT
lj_cutoff              $cut_i2i
dh_ionicstrength       $salt   # mol/l
dh_cutoff              $cut_i2i
g2g_cutoff             $cut_g2g

cuboid_len             150     # Box side length Angstrom

transrot_transdp       80      # Molecular translation parameter
transrot_rotdp         6       # Molecular rotation parameter
transrot_runfraction   1.0
swapmv_runfraction     0.2     # Proton titration run fraction

# Molecular species - currently only two different kinds
molecule1_N            10
molecule1              testmolecule.aam
molecule2_N            0
molecule2              testmolecule.aam 
molecule_plane         yes
molecule_offset        $Rp     # Elevate protein mass center above surface

# Explicit ions - add up to ten. To be used for multivalent ions
tion1                  Ca
nion1                  0
" > wall.input
}

# Executable
exe=./jana-wall

# Calc. Debye length and cutoff (3xDebye length)
salt=0.01 # salt concentration
Rp=20     # max protein radius
D=`python -c "from math import sqrt; print 3.04/sqrt($salt)"`
cut_i2i=`python -c "print 4*$D"`
cut_g2g=`python -c "print $Rp+$Rp+$cut_i2i"`

for pH in 6.3
do
  #rm -fR state
  micro=10000
  mkinput
  $exe
done

