#!/bin/sh
#
# Joao Henriques
# 2014.10.16
#
function mkinput() {
echo "##### files needed #####
atomlist                 param.json
eq_processfile           param.json
molecule                 molecule.aam

##### MC loop #####
loop_macrosteps          10
loop_microsteps          100

##### general parameters #####
cuboid_len               3000             # > 2 * peptide full length
# temperature            298              # K
# epsilon_r              78.7             # Water dielectric const
# dh_debyelength         10.8             # A
dh_ionicstrength         0.15             # mol/dm^3
r12rep_eps               0.2              # kT
r12repex_eps             -0.199999        # kT
gouychapman_rho          -3.1207e-3       # e/A^2
gouychapman_linearize    no               # non-linear GC
harmonic_eqdist          4.9              # A
harmonic_forceconst      0.76             # kT/A^2
squarewell_depth         0.5              # kT
squarewell_threshold     3                # A
stickywall_type          lj               # LJ potential
stickywall_depth         2.75             # kT
# stickywall_threshold     3                # A
# bin_min                  xxx              # A
# bin_max                  yyy              # A

##### move parameters #####
mv_particle_genericdp    5                # ~= harmonic_eqdist 
transrot_transdp         50               # window size
transrot_rotdp           3                # rads
crank_dp                 3                # rads
crank_minlen             1
crank_maxlen             210              # N-1
pivot_dp                 3                # rads
pivot_minlen             1
pivot_maxlen             210              # N-1

##### misc #####
test_stable              no" > simulation.input
}
# ext params
dens=1.4 # g/L
pH=8.5
# run stuff
scr=/Volumes/Data1/joaoh/simulations/stickywallclass_testing/sims
exe=/Volumes/Data1/joaoh/simulations/stickywallclass_testing/program
mdl=/Volumes/Data1/joaoh/simulations/stickywallclass_testing/model
if [ -x $exe ]; then
    rm -f param.json simulation.{input,gro,pqr,state} molecule.aam surf_{mc,res}_dist.dat netq_dist.dat rg2_dist.dat rg_step.dat
    $scr/mkinput.py json $dens                  $pH   > param.json
    $scr/mkinput.py aam  $mdl/b-casein_A1.fasta $dens > molecule.aam
    mkinput
    $exe/peptide_surface
    rc=$?
    exit $rc
fi
exit 1