#!/bin/sh
#
# Joao Henriques
# 2014.05.23
#
# Script is not ready to use, some values are ill-defined on purpose.
# It's just a template.
#
function mkinput() {
echo "##### files needed #####
atomlist                 param.json
eq_processfile           param.json
molecule                 molecule.aam

##### MC loop #####
loop_macrosteps          100
loop_microsteps          100000

##### general parameters #####
cuboid_len               3000             # > 2 * peptide full length
# temperature            298              # K
# epsilon_r              78.7             # Water dielectric const
# dh_debyelength         10.8             # A
dh_ionicstrength         0.15             # mol/dm^3
r12rep_eps               0.2              # kT
r12repex_eps             -0.199999        # kT
gouychapman_rho          -3.1207e-3       # e/A^2
gouychapman_linearize    no               # non-linear GC
harmonic_eqdist          4.9              # A
harmonic_forceconst      0.76             # kT/A^2
squarewell_depth         0.5              # kT
squarewell_threshold     3                # A
hydrwl_type              lj               # LJ potential
hydrwl_depth             2.75             # kT
# hydrwl_threshold         3                # A
bin_min                  xxx              # A
bin_max                  yyy              # A

##### move parameters #####
mv_particle_genericdp    5                # ~= harmonic_eqdist 
transrot_transdp         50               # window size
transrot_rotdp           3                # rads
crank_dp                 3                # rads
crank_minlen             1
crank_maxlen             210              # N-1
pivot_dp                 3                # rads
pivot_minlen             1
pivot_maxlen             210              # N-1

##### misc #####
test_stable              no" > simulation.input
}
# ext params
dens=zzz # g/L
pH=kkk
# run stuff
scr="path_to_script"
exe="path_to_program"
mdl="path_to_peptide_model"
if [ -x $exe ]; then
    rm -f param.json simulation.{input,gro,pqr,state} molecule.aam surf_{mc,res}_dist.dat netq_dist.dat rg2_dist.dat rg_step.dat
    $scr/mkinput.py json $dens $pH > param.json
    $scr/mkinput.py aam $mdl/"name".fasta $dens > molecule.aam
    mkinput
    $exe
    rc=$?
    exit $rc
fi
exit 1