#!/bin/bash

#-----------------------------------------------------------
# Create user input file
#-----------------------------------------------------------
function mkinput() {
echo "
Atom  HD      +0     $radius    $epsilon    1       no
Atom  TL      -0     $radius    $epsilon    1       no
" > membrane.atoms

echo "3
 HD  0   0.00   0.00   0.00    0.0   1  $radius
 TL  1   4.00   0.00   0.00    0.0   1  $radius
 TL  2   8.00   0.00   0.00    0.0   1  $radius
" > lipid.aam

echo "
atomlist               membrane.atoms
loop_macrosteps        10
loop_microsteps        $micro
cuboid_len             $box      # Box side length Angstrom

temperature            298       # Kelvin
epsilon_r              78.7      # Water dielectric const
lipid_epsilon          $epsilon  # kT
lipid_sigma            $sigma    # Å
cosattract_eps         $epsilon
cosattract_wc          "`python -c "print $sigma*1.4"`"
cosattract_rc          "`python -c "print $sigma*2**(1/6.)"`"

polymer_N              $Nlipid
polymer_file           lipid.aam

mv_particle_genericdp  3.
transrot_transdp       3
transrot_rotdp         0.5
" > membrane.input
}

#-----------------------------------------------------------
# Run simulation
#-----------------------------------------------------------
exe=./mlund-membrane
epsilon=1
sigma=10
radius=`python -c "print 0.5*$sigma"`
Nlipid=100
box=`python -c "print ( ($Nlipid/1000.)*25**3 )**(1/3.)*$sigma"`
#rm -f state
micro=10000
mkinput
$exe

