#!/bin/bash

#-----------------------------------------------------------
# Create user input file
#-----------------------------------------------------------
function mkinput() {
echo "
Atom  HD      +0     $radius    $epsilon    1       no
Atom  TL      -0     $radius    $epsilon    1       no
Atom  PEP      0     $radius    $epsilon    1       no
Atom  ASP     -1     3.6        0.1         110     no
Atom  HASP     0     3.6        0.1         110     no
Atom  CTR     -1     2.0        0.1         16      no
Atom  HCTR     0     2.0        0.1         16      no
Atom  GLU     -1     3.8        0.1         122     no
Atom  HGLU     0     3.8        0.1         122     no
Atom  HIS      0     3.9        0.1         130     no
Atom  HHIS     1     3.9        0.1         130     no
Atom  NTR      0     2.0        0.1         14      no
Atom  HNTR     1     2.0        0.1         14      no
Atom  TYR     -1     4.1        0.1         154     no
Atom  HTYR     0     4.1        0.1         154     no
Atom  LYS      0     3.7        0.1         116     no
Atom  HLYS     1     3.7        0.1         116     no
Atom  CYS     -1     3.6        0.1         103     no 
Atom  HCYS     0     3.6        0.1         103     no 
Atom  ARG      0     4.0        0.1         144     no
Atom  HARG     1     4.0        0.1         144     no
" > membrane.atoms

echo "3
 HD  0   0.00   0.00   0.00    0.0   1  $radius
 TL  1   4.00   0.00   0.00    0.0   1  $radius
 TL  2   8.00   0.00   0.00    0.0   1  $radius
" > lipid.aam

echo "10
 NTR  0  10.00   0.00   2.00    0.0   1  2.0
 ARG  0  10.00   0.00   5.00    0.0   1  4.0
 ARG  1  11.00  19.00   0.00    0.0   1  4.0
 ARG  2  12.00  18.00   0.00    0.0   1  4.0
 ARG  3  13.00  17.00   0.00    0.0   1  4.0
 ARG  3  14.00  16.00   0.00    0.0   1  4.0
 ARG  3  15.00  15.00   0.00    0.0   1  4.0
 ARG  3  16.00  14.00   0.00    0.0   1  4.0
 ARG  3  17.00  13.00   0.00    0.0   1  4.0
 ARG  3  18.00  12.00   0.00    0.0   1  4.0
 ARG  3  18.00  12.00   0.00    0.0   1  4.0
 CTR  3  19.00  11.00   2.00    0.0   1  2.0
" > peptide.aam

echo "
Process  HASP  ASP     4.0     $pH
Process  HCTR  CTR     2.6     $pH
Process  HGLU  GLU     4.4     $pH
Process  HHIS  HIS     6.3     $pH
Process  HNTR  NTR     7.5     $pH
Process  HTYR  TYR     9.6     $pH
Process  HLYS  LYS     10.4    $pH
Process  HCYS  CYS     10.8    $pH
Process  HARG  ARG     12.0    $pH
" > processes

echo "
atomlist               membrane.atoms
eq_processfile         processes

loop_macrosteps        5
loop_microsteps        $micro
cuboid_len             -1        # Box side length Angstrom
cuboid_xlen            $box
cuboid_ylen            $box
cuboid_zlen            "`python -c "print $box*2"`"

temperature            298       # Kelvin
epsilon_r              80        # Water dielectric const
dh_ionicstrength       0.050     # mol/l
excess_polarization    $excesspol
lipid_epsilon          $epsilon  # kT
lipid_sigma            $sigma    # Å
lipid_chargefraction   0.3
lipid_N                $Nlipid
lipid_file             lipid.aam

polymer_forceconst     0.76
polymer_eqdist         $sigma
polymer_file           peptide.aam
polymer_transdp        10
polymer_rotdp          2

cosattract_eps         $epsilon
cosattract_wc          "`python -c "print $sigma*1.4"`"
cosattract_rc          "`python -c "print $sigma*2**(1/6.)"`"

mv_particle_genericdp  10.
transrot_transdp       3
transrot_rotdp         0.5
" > membrane.input
}

#-----------------------------------------------------------
# Run simulation
#-----------------------------------------------------------
exe=./mlund-membrane
pH=6.3
epsilon=1
sigma=10
radius=`python -c "print 0.5*$sigma"`
Nlipid=100
box=`python -c "print ( ($Nlipid/1000.)*25**2 )**(1/2.)*$sigma"`
#rm -f state

for excesspol in -0 -4 -2 -16 -8 -32
do
  out="pol${excesspol}_N${Nlipid}"
  rm -fR *state 
  micro=1000
  mkinput
  $exe > $out.eq

  micro=500000
  mkinput
  $exe > $out.out
  mv pepmem.dat $out.dat
  mv confout.pqr $out.pqr
  mv traj.xtc $out.xtc
  mv zpepmem.dat $out.z.dat
done
