#!/bin/bash

#-----------------------------------------------------------
# Create user input file
#-----------------------------------------------------------
function mkinput() {
echo "
Atom  HD      +0     $radius    $epsilon    1       no
Atom  TL      -0     $radius    $epsilon    1       no
Atom  PEP      0     $radius    $epsilon    1       no
Atom  HIS      0     3.9        0.1         130     no
Atom  HHIS     1     3.9        0.1         130     no
" > membrane.atoms

echo "3
 HD  0   0.00   0.00   0.00    0.0   1  $radius
 TL  1   4.00   0.00   0.00    0.0   1  $radius
 TL  2   8.00   0.00   0.00    0.0   1  $radius
" > lipid.aam

echo "4
 HIS  0  10.00   0.00   0.00    0.0   1  3.9
 HIS  1  20.00   0.00   0.00    0.0   1  3.9
 HIS  2  10.00  10.00   0.00    0.0   1  3.9
 HIS  3  20.00  10.00   0.00    0.0   1  3.9
" > peptide.aam

echo "
Process  HASP  ASP     4.0     $pH
Process  HCTR  CTR     2.6     $pH
Process  HGLU  GLU     4.4     $pH
Process  HHIS  HIS     6.3     $pH
Process  HNTR  NTR     7.5     $pH
Process  HTYR  TYR     9.6     $pH
Process  HLYS  LYS     10.4    $pH
Process  HCYS  CYS     10.8    $pH
Process  HARG  ARG     12.0    $pH
" > processes

echo "
atomlist               membrane.atoms
eq_processfile         processes

loop_macrosteps        5
loop_microsteps        $micro
cuboid_len             -1        # Box side length Angstrom
cuboid_xlen            $box
cuboid_ylen            $box
cuboid_zlen            "`python -c "print $box*2"`"

temperature            298       # Kelvin
epsilon_r              8000     # Water dielectric const
dh_ionicstrength       9000.1       # mol/l
lipid_epsilon          $epsilon  # kT
lipid_sigma            $sigma    # Å
lipid_areapercharge    300
lipid_N                $Nlipid
lipid_file             lipid.aam

polymer_forceconst     0.05
polymer_eqdist         $sigma
polymer_file           peptide.aam
polymer_transdp        10
polymer_rotdp          2

cosattract_eps         $epsilon
cosattract_wc          "`python -c "print $sigma*1.4"`"
cosattract_rc          "`python -c "print $sigma*2**(1/6.)"`"

mv_particle_genericdp  3.
transrot_transdp       3
transrot_rotdp         0.5
" > membrane.input
}

#-----------------------------------------------------------
# Run simulation
#-----------------------------------------------------------
exe=./mlund-membrane
pH=6.3
epsilon=1
sigma=10
radius=`python -c "print 0.5*$sigma"`
Nlipid=100
box=`python -c "print ( ($Nlipid/1000.)*25**2 )**(1/2.)*$sigma"`
#rm -f state
micro=300
mkinput
$exe

