#!/bin/bash

source_tests_dir="`dirname $0`"
cp -f $source_tests_dir/membrane.test . 2> /dev/null
cp -f $source_tests_dir/membrane.state state 2> /dev/null

#-----------------------------------------------------------
# Create user input file
#-----------------------------------------------------------
function mkinput() {
echo '{
  "atomlist" : {
    "HD" : { "r":5.0, "dp":4.0 },
    "TL" : { "r":5.0, "dp":2.0 }
  },

  "moleculelist" : {
    "lipid" : { "structure":"lipid.aam", "Ninit":'$Nlipid' }
  },

  "energy" : {
    "nonbonded" : {
      "cutoff_g2g" : 40,
      "coulomb" : { "epsr" : 80.0, "ionicstrength":0.05 },
      "cosattract" : {
        "wc":'`python -c "print($sigma*1.6)"`',
        "rc":'`python -c "print($sigma*2**(1/6.))"`', "eps":'$epsilon' }
    }
  },
    "analysis" : {
        "virial" :    { "nstep":5 },
        "xtcfile" :   { "file": "membrane.xtc", "nstep":20 },
        "pqrfile" :   { "file": "membrane.pqr" },
        "statefile" : { "file": "state" }
        },
  "moves" : {
    "atomtranslate" : { "lipid" : { "prob":0.5 } },
    "pivot"         : { "lipid" : { "permol":true,  "minlen":1, "maxlen":2, "dp":6 } },
    "moltransrot"   : { "lipid" : { "permol":true, "dp":2.0, "dprot":0.5 } },
    "isobaric"      : { "dp":0.5, "pressure":0, "prob":0.2 }
  },

  "system" : {
    "temperature"  : 298,
    "cuboid"       : { "scaledir":"xy",
                       "xyzlen" : "'`python -c "print($box, $box, $box*2)"`'" },
    "mcloop"       : { "macro":10, "micro":1000 },
    "unittest"     : { "testfile":"membrane.test", "stable":false },
    "lipid_epsilon": '$epsilon',
    "lipid_sigma"  : '$sigma'
  }
}' > membrane.json

echo "3
 HD  0 0.00  0.00   0.00   0.0   1  "`python -c "print (0.5*$sigma)"`"
 TL  1 0.00  0.00   5.00   0.0   1  "`python -c "print (0.5*$sigma)"`"
 TL  2 0.00  0.00  10.00   0.0   1  "`python -c "print (0.5*$sigma)"`"
" > lipid.aam
}

#-----------------------------------------------------------
# Run simulation
#-----------------------------------------------------------
exe=./membrane
if [ -x $exe ]; then
  pH=6.3
  epsilon=1
  sigma=10
  Nlipid=100
  box=`python -c "print (( ($Nlipid/1000.)*25**2 )**(1/2.)*$sigma)"`
  mkinput
  $exe
  rc=$?
  #rm -f membrane.json
  exit $rc
fi
exit 1

