#!/usr/bin/env python
import webbrowser
from os import path

filename = path.dirname( path.realpath(__file__) ) + '/../share/faunus/manual.html'
if path.exists(filename):
    webbrowser.open('file://'+filename)
else:
   print('faunus manual not installed')

