package:
  name: faunus
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/mlund/faunus.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script:
    - export CC=clang     # [osx]
    - export CXX=clang++  # [osx]
    - cmake -DENABLE_MPI=on -DENABLE_OPENMP=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX
    - make
    - make install
    - ctest --output-on-failure

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp   # [osx]
    - python
    - pandoc 2.*
    - pypandoc 1.*
    - beautifulsoup4
    - ruamel_yaml
    - cmake >=3.11.4
    - numpy 1.*
    - matplotlib
    - nbconvert
    - notebook
    - jupyter
    - openmpi 1.6.*  # [osx]
    - openmpi 3.1.*  # [linux64]
  run:
    - llvm-openmp    # [osx]
    - openmpi 1.6.*  # [osx]
    - openmpi 3.1.*  # [linux64]
    - ruamel_yaml
    - pygments
    - numpy 1.*
    - python
    - jinja2

about:
  home: http://mlund.github.io/faunus
  summary: A Framework for Molecular Monte Carlo Simulations
  license: MIT
  doc_url: http://mlund.github.io/faunus
  dev_url: https://github.com/mlund/faunus
