*----------------------------------------------------------------------*
*                                                                      *
* 1.0d-4 = 3f1a36e2                                                    *
* 1.0d-5 = 3ee4f8b5                                                    *
* x-max  = 4066d466                                                    *
*----------------------------------------------------------------------*
      Parameter (nPol=4, nShift=16)
      Parameter (MxTab=1700)
      Common /vsTab/ c(0:MxTab)
      Data indx/z'3f170000'/
      Data ind0/z'3f180000'/
      Data ind1/z'40680000'/
      Data ind2/z'00010000'/
c     Data indx/1058471936/ 
c     Data ind0/1058537472/ 
c     Data ind1/1080557568/ 
c     Data ind2/65536/       

