#ifndef VORONOTALT_PARALLELIZATION_CONFIGURATION_H_
#define VORONOTALT_PARALLELIZATION_CONFIGURATION_H_

#ifdef _OPENMP
#define VORONOTALT_OPENMP
#endif

#endif /* VORONOTALT_PARALLELIZATION_CONFIGURATION_H_ */
